// Code generated by protoc-gen-gogo.
// source: tlsconfig.proto
// DO NOT EDIT!

package proto

import proto1 "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/protobuf/gogoproto"

import strconv "strconv"

import bytes "bytes"

import strings "strings"
import reflect "reflect"

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type TLSVersion int32

const (
	TLSVersion_UNSPECIFIED TLSVersion = 0
	VERSION_SSL30          TLSVersion = 768
	VERSION_TLS10          TLSVersion = 769
	VERSION_TLS11          TLSVersion = 770
	VERSION_TLS12          TLSVersion = 771
)

var TLSVersion_name = map[int32]string{
	0:   "TLSVersion_UNSPECIFIED",
	768: "VERSION_SSL30",
	769: "VERSION_TLS10",
	770: "VERSION_TLS11",
	771: "VERSION_TLS12",
}
var TLSVersion_value = map[string]int32{
	"TLSVersion_UNSPECIFIED": 0,
	"VERSION_SSL30":          768,
	"VERSION_TLS10":          769,
	"VERSION_TLS11":          770,
	"VERSION_TLS12":          771,
}

func (TLSVersion) EnumDescriptor() ([]byte, []int) { return fileDescriptorTlsconfig, []int{0} }

type ClientAuthType int32

const (
	NO_CLIENT_CERT                 ClientAuthType = 0
	REQUEST_CLIENT_CERT            ClientAuthType = 1
	REQUIRE_ANY_CLIENT_CERT        ClientAuthType = 2
	VERIFY_CLIENT_CERT_IF_GIVEN    ClientAuthType = 3
	REQUIRE_AND_VERIFY_CLIENT_CERT ClientAuthType = 4
)

var ClientAuthType_name = map[int32]string{
	0: "NO_CLIENT_CERT",
	1: "REQUEST_CLIENT_CERT",
	2: "REQUIRE_ANY_CLIENT_CERT",
	3: "VERIFY_CLIENT_CERT_IF_GIVEN",
	4: "REQUIRE_AND_VERIFY_CLIENT_CERT",
}
var ClientAuthType_value = map[string]int32{
	"NO_CLIENT_CERT":                 0,
	"REQUEST_CLIENT_CERT":            1,
	"REQUIRE_ANY_CLIENT_CERT":        2,
	"VERIFY_CLIENT_CERT_IF_GIVEN":    3,
	"REQUIRE_AND_VERIFY_CLIENT_CERT": 4,
}

func (ClientAuthType) EnumDescriptor() ([]byte, []int) { return fileDescriptorTlsconfig, []int{1} }

type CipherSuite int32

const (
	CipherSuite_UNSPECIFIED                 CipherSuite = 0
	TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256   CipherSuite = 49199
	TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384   CipherSuite = 49200
	TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256   CipherSuite = 49191
	TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA      CipherSuite = 49171
	TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA      CipherSuite = 49172
	TLS_RSA_WITH_AES_128_GCM_SHA256         CipherSuite = 156
	TLS_RSA_WITH_AES_256_GCM_SHA384         CipherSuite = 157
	TLS_RSA_WITH_AES_128_CBC_SHA256         CipherSuite = 60
	TLS_RSA_WITH_AES_128_CBC_SHA            CipherSuite = 47
	TLS_RSA_WITH_AES_256_CBC_SHA            CipherSuite = 53
	TLS_RSA_WITH_RC4_128_SHA                CipherSuite = 5
	TLS_RSA_WITH_3DES_EDE_CBC_SHA           CipherSuite = 10
	TLS_ECDHE_ECDSA_WITH_RC4_128_SHA        CipherSuite = 49159
	TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA    CipherSuite = 49161
	TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA    CipherSuite = 49162
	TLS_ECDHE_RSA_WITH_RC4_128_SHA          CipherSuite = 49169
	TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA     CipherSuite = 49170
	TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256 CipherSuite = 49195
	TLS_FALLBACK_SCSV                       CipherSuite = 22016
)

var CipherSuite_name = map[int32]string{
	0:     "CipherSuite_UNSPECIFIED",
	49199: "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
	49200: "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
	49191: "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256",
	49171: "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA",
	49172: "TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA",
	156:   "TLS_RSA_WITH_AES_128_GCM_SHA256",
	157:   "TLS_RSA_WITH_AES_256_GCM_SHA384",
	60:    "TLS_RSA_WITH_AES_128_CBC_SHA256",
	47:    "TLS_RSA_WITH_AES_128_CBC_SHA",
	53:    "TLS_RSA_WITH_AES_256_CBC_SHA",
	5:     "TLS_RSA_WITH_RC4_128_SHA",
	10:    "TLS_RSA_WITH_3DES_EDE_CBC_SHA",
	49159: "TLS_ECDHE_ECDSA_WITH_RC4_128_SHA",
	49161: "TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA",
	49162: "TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA",
	49169: "TLS_ECDHE_RSA_WITH_RC4_128_SHA",
	49170: "TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA",
	49195: "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256",
	22016: "TLS_FALLBACK_SCSV",
}
var CipherSuite_value = map[string]int32{
	"CipherSuite_UNSPECIFIED":                 0,
	"TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256":   49199,
	"TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384":   49200,
	"TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256":   49191,
	"TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA":      49171,
	"TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA":      49172,
	"TLS_RSA_WITH_AES_128_GCM_SHA256":         156,
	"TLS_RSA_WITH_AES_256_GCM_SHA384":         157,
	"TLS_RSA_WITH_AES_128_CBC_SHA256":         60,
	"TLS_RSA_WITH_AES_128_CBC_SHA":            47,
	"TLS_RSA_WITH_AES_256_CBC_SHA":            53,
	"TLS_RSA_WITH_RC4_128_SHA":                5,
	"TLS_RSA_WITH_3DES_EDE_CBC_SHA":           10,
	"TLS_ECDHE_ECDSA_WITH_RC4_128_SHA":        49159,
	"TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA":    49161,
	"TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA":    49162,
	"TLS_ECDHE_RSA_WITH_RC4_128_SHA":          49169,
	"TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA":     49170,
	"TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256": 49195,
	"TLS_FALLBACK_SCSV":                       22016,
}

func (CipherSuite) EnumDescriptor() ([]byte, []int) { return fileDescriptorTlsconfig, []int{2} }

type CurveID int32

const (
	CurveID_UNSPECIFIED CurveID = 0
	P256                CurveID = 23
	P384                CurveID = 24
	P521                CurveID = 25
)

var CurveID_name = map[int32]string{
	0:  "CurveID_UNSPECIFIED",
	23: "P256",
	24: "P384",
	25: "P521",
}
var CurveID_value = map[string]int32{
	"CurveID_UNSPECIFIED": 0,
	"P256":                23,
	"P384":                24,
	"P521":                25,
}

func (CurveID) EnumDescriptor() ([]byte, []int) { return fileDescriptorTlsconfig, []int{3} }

// TLSConfig structure is used to configure a TLS client or server.
type TLSConfig struct {
	// Certificates contains one or more certificate chains
	// to present to the other side of the connection.
	// Server configurations must include at least one certificate.
	Certificates []*CertificateAndKeyID `protobuf:"bytes,1,rep,name=certificates" json:"certificates,omitempty"`
	// RootCAs defines the set of root certificate authorities
	// that clients use when verifying server certificates.
	// If RootCAs is nil, TLS uses the host's root CA set.
	// The certificates are expected in DER format.
	RootCAs [][]byte `protobuf:"bytes,3,rep,name=root_cas,json=rootCas" json:"root_cas,omitempty"`
	// NextProtos is a list of supported, application level protocols.
	NextProtos []string `protobuf:"bytes,4,rep,name=next_protos,json=nextProtos" json:"next_protos,omitempty"`
	// ServerName is used to verify the hostname on the returned
	// certificates. It is also included in the client's handshake to support
	// virtual hosting.
	ServerName string `protobuf:"bytes,5,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"`
	// ClientAuth determines the server's policy for
	// TLS Client Authentication. The default is NoClientCert.
	ClientAuth ClientAuthType `protobuf:"varint,6,opt,name=client_auth,json=clientAuth,proto3,enum=proto.ClientAuthType" json:"client_auth,omitempty"`
	// ClientCAs defines the set of root certificate authorities that servers
	// use if required to verify a client certificate by the policy in
	// ClientAuth. The certificates are expected in DER format.
	ClientCAs [][]byte `protobuf:"bytes,7,rep,name=client_cas,json=clientCas" json:"client_cas,omitempty"`
	// CipherSuites is a list of supported cipher suites. If CipherSuites
	// is nil, TLS uses a list of suites supported by the implementation.
	CipherSuites []CipherSuite `protobuf:"varint,8,rep,packed,name=cipher_suites,json=cipherSuites,enum=proto.CipherSuite" json:"cipher_suites,omitempty"`
	// PreferServerCipherSuites controls whether the server selects the
	// client's most preferred ciphersuite, or the server's most preferred
	// ciphersuite. If true then the server's preference, as expressed in
	// the order of elements in CipherSuites, is used.
	PreferServerCipherSuites bool `protobuf:"varint,9,opt,name=prefer_server_cipher_suites,json=preferServerCipherSuites,proto3" json:"prefer_server_cipher_suites,omitempty"`
	// SessionTicketsEnabled may be set to true to enable session ticket
	// (resumption) support. Enabling session tickets limits forward secrecy to
	// until after the lifetime of the session ticket key (which, by default,
	// lives as long as the server process).
	SessionTicketsEnabled bool `protobuf:"varint,10,opt,name=session_tickets_enabled,json=sessionTicketsEnabled,proto3" json:"session_tickets_enabled,omitempty"`
	// SessionTicketKey (32 bytes) is used by TLS servers to provide session
	// resumption. See RFC 5077. If zero, it will be filled with random data
	// before the first server handshake.
	//
	// If multiple servers are terminating connections for the same host
	// they should all have the same SessionTicketKey. If the
	// SessionTicketKey leaks, previously recorded and future TLS
	// connections using that key are compromised.
	SessionTicketKeyID string `protobuf:"bytes,11,opt,name=session_ticket_key_id,json=sessionTicketKeyId,proto3" json:"session_ticket_key_id,omitempty"`
	// MinVersion contains the minimum SSL/TLS version that is acceptable.
	// If zero, then SSLv3 is taken as the minimum.
	MinVersion TLSVersion `protobuf:"varint,12,opt,name=min_version,json=minVersion,proto3,enum=proto.TLSVersion" json:"min_version,omitempty"`
	// MaxVersion contains the maximum SSL/TLS version that is acceptable.
	// If zero, then the maximum version supported by this package is used,
	// which is currently TLS 1.2.
	MaxVersion TLSVersion `protobuf:"varint,13,opt,name=max_version,json=maxVersion,proto3,enum=proto.TLSVersion" json:"max_version,omitempty"`
	// CurvePreferences contains the elliptic curves that will be used in
	// an ECDHE handshake, in preference order. If empty, the default will
	// be used.
	CurvePreferences []CurveID `protobuf:"varint,14,rep,packed,name=curve_preferences,json=curvePreferences,enum=proto.CurveID" json:"curve_preferences,omitempty"`
}

func (m *TLSConfig) Reset()                    { *m = TLSConfig{} }
func (*TLSConfig) ProtoMessage()               {}
func (*TLSConfig) Descriptor() ([]byte, []int) { return fileDescriptorTlsconfig, []int{0} }

func (m *TLSConfig) GetCertificates() []*CertificateAndKeyID {
	if m != nil {
		return m.Certificates
	}
	return nil
}

func (m *TLSConfig) GetRootCAs() [][]byte {
	if m != nil {
		return m.RootCAs
	}
	return nil
}

func (m *TLSConfig) GetNextProtos() []string {
	if m != nil {
		return m.NextProtos
	}
	return nil
}

func (m *TLSConfig) GetServerName() string {
	if m != nil {
		return m.ServerName
	}
	return ""
}

func (m *TLSConfig) GetClientAuth() ClientAuthType {
	if m != nil {
		return m.ClientAuth
	}
	return NO_CLIENT_CERT
}

func (m *TLSConfig) GetClientCAs() [][]byte {
	if m != nil {
		return m.ClientCAs
	}
	return nil
}

func (m *TLSConfig) GetCipherSuites() []CipherSuite {
	if m != nil {
		return m.CipherSuites
	}
	return nil
}

func (m *TLSConfig) GetPreferServerCipherSuites() bool {
	if m != nil {
		return m.PreferServerCipherSuites
	}
	return false
}

func (m *TLSConfig) GetSessionTicketsEnabled() bool {
	if m != nil {
		return m.SessionTicketsEnabled
	}
	return false
}

func (m *TLSConfig) GetSessionTicketKeyID() string {
	if m != nil {
		return m.SessionTicketKeyID
	}
	return ""
}

func (m *TLSConfig) GetMinVersion() TLSVersion {
	if m != nil {
		return m.MinVersion
	}
	return TLSVersion_UNSPECIFIED
}

func (m *TLSConfig) GetMaxVersion() TLSVersion {
	if m != nil {
		return m.MaxVersion
	}
	return TLSVersion_UNSPECIFIED
}

func (m *TLSConfig) GetCurvePreferences() []CurveID {
	if m != nil {
		return m.CurvePreferences
	}
	return nil
}

type CertificateAndKeyID struct {
	// Certificate contains the public certificates in DER format, leaf first.
	Certificate [][]byte `protobuf:"bytes,1,rep,name=certificate" json:"certificate,omitempty"`
	KeyID       string   `protobuf:"bytes,2,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	OCSPStaple  []byte   `protobuf:"bytes,3,opt,name=OCSP_staple,json=OCSPStaple,proto3" json:"OCSP_staple,omitempty"`
}

func (m *CertificateAndKeyID) Reset()                    { *m = CertificateAndKeyID{} }
func (*CertificateAndKeyID) ProtoMessage()               {}
func (*CertificateAndKeyID) Descriptor() ([]byte, []int) { return fileDescriptorTlsconfig, []int{1} }

func (m *CertificateAndKeyID) GetCertificate() [][]byte {
	if m != nil {
		return m.Certificate
	}
	return nil
}

func (m *CertificateAndKeyID) GetKeyID() string {
	if m != nil {
		return m.KeyID
	}
	return ""
}

func (m *CertificateAndKeyID) GetOCSPStaple() []byte {
	if m != nil {
		return m.OCSPStaple
	}
	return nil
}

func init() {
	proto1.RegisterType((*TLSConfig)(nil), "proto.TLSConfig")
	proto1.RegisterType((*CertificateAndKeyID)(nil), "proto.CertificateAndKeyID")
	proto1.RegisterEnum("proto.TLSVersion", TLSVersion_name, TLSVersion_value)
	proto1.RegisterEnum("proto.ClientAuthType", ClientAuthType_name, ClientAuthType_value)
	proto1.RegisterEnum("proto.CipherSuite", CipherSuite_name, CipherSuite_value)
	proto1.RegisterEnum("proto.CurveID", CurveID_name, CurveID_value)
}
func (x TLSVersion) String() string {
	s, ok := TLSVersion_name[int32(x)]
	if ok {
		return s
	}
	return strconv.Itoa(int(x))
}
func (x ClientAuthType) String() string {
	s, ok := ClientAuthType_name[int32(x)]
	if ok {
		return s
	}
	return strconv.Itoa(int(x))
}
func (x CipherSuite) String() string {
	s, ok := CipherSuite_name[int32(x)]
	if ok {
		return s
	}
	return strconv.Itoa(int(x))
}
func (x CurveID) String() string {
	s, ok := CurveID_name[int32(x)]
	if ok {
		return s
	}
	return strconv.Itoa(int(x))
}
func (this *TLSConfig) VerboseEqual(that interface{}) error {
	if that == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that == nil && this != nil")
	}

	that1, ok := that.(*TLSConfig)
	if !ok {
		that2, ok := that.(TLSConfig)
		if ok {
			that1 = &that2
		} else {
			return fmt.Errorf("that is not of type *TLSConfig")
		}
	}
	if that1 == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that is type *TLSConfig but is nil && this != nil")
	} else if this == nil {
		return fmt.Errorf("that is type *TLSConfig but is not nil && this == nil")
	}
	if len(this.Certificates) != len(that1.Certificates) {
		return fmt.Errorf("Certificates this(%v) Not Equal that(%v)", len(this.Certificates), len(that1.Certificates))
	}
	for i := range this.Certificates {
		if !this.Certificates[i].Equal(that1.Certificates[i]) {
			return fmt.Errorf("Certificates this[%v](%v) Not Equal that[%v](%v)", i, this.Certificates[i], i, that1.Certificates[i])
		}
	}
	if len(this.RootCAs) != len(that1.RootCAs) {
		return fmt.Errorf("RootCAs this(%v) Not Equal that(%v)", len(this.RootCAs), len(that1.RootCAs))
	}
	for i := range this.RootCAs {
		if !bytes.Equal(this.RootCAs[i], that1.RootCAs[i]) {
			return fmt.Errorf("RootCAs this[%v](%v) Not Equal that[%v](%v)", i, this.RootCAs[i], i, that1.RootCAs[i])
		}
	}
	if len(this.NextProtos) != len(that1.NextProtos) {
		return fmt.Errorf("NextProtos this(%v) Not Equal that(%v)", len(this.NextProtos), len(that1.NextProtos))
	}
	for i := range this.NextProtos {
		if this.NextProtos[i] != that1.NextProtos[i] {
			return fmt.Errorf("NextProtos this[%v](%v) Not Equal that[%v](%v)", i, this.NextProtos[i], i, that1.NextProtos[i])
		}
	}
	if this.ServerName != that1.ServerName {
		return fmt.Errorf("ServerName this(%v) Not Equal that(%v)", this.ServerName, that1.ServerName)
	}
	if this.ClientAuth != that1.ClientAuth {
		return fmt.Errorf("ClientAuth this(%v) Not Equal that(%v)", this.ClientAuth, that1.ClientAuth)
	}
	if len(this.ClientCAs) != len(that1.ClientCAs) {
		return fmt.Errorf("ClientCAs this(%v) Not Equal that(%v)", len(this.ClientCAs), len(that1.ClientCAs))
	}
	for i := range this.ClientCAs {
		if !bytes.Equal(this.ClientCAs[i], that1.ClientCAs[i]) {
			return fmt.Errorf("ClientCAs this[%v](%v) Not Equal that[%v](%v)", i, this.ClientCAs[i], i, that1.ClientCAs[i])
		}
	}
	if len(this.CipherSuites) != len(that1.CipherSuites) {
		return fmt.Errorf("CipherSuites this(%v) Not Equal that(%v)", len(this.CipherSuites), len(that1.CipherSuites))
	}
	for i := range this.CipherSuites {
		if this.CipherSuites[i] != that1.CipherSuites[i] {
			return fmt.Errorf("CipherSuites this[%v](%v) Not Equal that[%v](%v)", i, this.CipherSuites[i], i, that1.CipherSuites[i])
		}
	}
	if this.PreferServerCipherSuites != that1.PreferServerCipherSuites {
		return fmt.Errorf("PreferServerCipherSuites this(%v) Not Equal that(%v)", this.PreferServerCipherSuites, that1.PreferServerCipherSuites)
	}
	if this.SessionTicketsEnabled != that1.SessionTicketsEnabled {
		return fmt.Errorf("SessionTicketsEnabled this(%v) Not Equal that(%v)", this.SessionTicketsEnabled, that1.SessionTicketsEnabled)
	}
	if this.SessionTicketKeyID != that1.SessionTicketKeyID {
		return fmt.Errorf("SessionTicketKeyID this(%v) Not Equal that(%v)", this.SessionTicketKeyID, that1.SessionTicketKeyID)
	}
	if this.MinVersion != that1.MinVersion {
		return fmt.Errorf("MinVersion this(%v) Not Equal that(%v)", this.MinVersion, that1.MinVersion)
	}
	if this.MaxVersion != that1.MaxVersion {
		return fmt.Errorf("MaxVersion this(%v) Not Equal that(%v)", this.MaxVersion, that1.MaxVersion)
	}
	if len(this.CurvePreferences) != len(that1.CurvePreferences) {
		return fmt.Errorf("CurvePreferences this(%v) Not Equal that(%v)", len(this.CurvePreferences), len(that1.CurvePreferences))
	}
	for i := range this.CurvePreferences {
		if this.CurvePreferences[i] != that1.CurvePreferences[i] {
			return fmt.Errorf("CurvePreferences this[%v](%v) Not Equal that[%v](%v)", i, this.CurvePreferences[i], i, that1.CurvePreferences[i])
		}
	}
	return nil
}
func (this *TLSConfig) Equal(that interface{}) bool {
	if that == nil {
		if this == nil {
			return true
		}
		return false
	}

	that1, ok := that.(*TLSConfig)
	if !ok {
		that2, ok := that.(TLSConfig)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		if this == nil {
			return true
		}
		return false
	} else if this == nil {
		return false
	}
	if len(this.Certificates) != len(that1.Certificates) {
		return false
	}
	for i := range this.Certificates {
		if !this.Certificates[i].Equal(that1.Certificates[i]) {
			return false
		}
	}
	if len(this.RootCAs) != len(that1.RootCAs) {
		return false
	}
	for i := range this.RootCAs {
		if !bytes.Equal(this.RootCAs[i], that1.RootCAs[i]) {
			return false
		}
	}
	if len(this.NextProtos) != len(that1.NextProtos) {
		return false
	}
	for i := range this.NextProtos {
		if this.NextProtos[i] != that1.NextProtos[i] {
			return false
		}
	}
	if this.ServerName != that1.ServerName {
		return false
	}
	if this.ClientAuth != that1.ClientAuth {
		return false
	}
	if len(this.ClientCAs) != len(that1.ClientCAs) {
		return false
	}
	for i := range this.ClientCAs {
		if !bytes.Equal(this.ClientCAs[i], that1.ClientCAs[i]) {
			return false
		}
	}
	if len(this.CipherSuites) != len(that1.CipherSuites) {
		return false
	}
	for i := range this.CipherSuites {
		if this.CipherSuites[i] != that1.CipherSuites[i] {
			return false
		}
	}
	if this.PreferServerCipherSuites != that1.PreferServerCipherSuites {
		return false
	}
	if this.SessionTicketsEnabled != that1.SessionTicketsEnabled {
		return false
	}
	if this.SessionTicketKeyID != that1.SessionTicketKeyID {
		return false
	}
	if this.MinVersion != that1.MinVersion {
		return false
	}
	if this.MaxVersion != that1.MaxVersion {
		return false
	}
	if len(this.CurvePreferences) != len(that1.CurvePreferences) {
		return false
	}
	for i := range this.CurvePreferences {
		if this.CurvePreferences[i] != that1.CurvePreferences[i] {
			return false
		}
	}
	return true
}
func (this *CertificateAndKeyID) VerboseEqual(that interface{}) error {
	if that == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that == nil && this != nil")
	}

	that1, ok := that.(*CertificateAndKeyID)
	if !ok {
		that2, ok := that.(CertificateAndKeyID)
		if ok {
			that1 = &that2
		} else {
			return fmt.Errorf("that is not of type *CertificateAndKeyID")
		}
	}
	if that1 == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that is type *CertificateAndKeyID but is nil && this != nil")
	} else if this == nil {
		return fmt.Errorf("that is type *CertificateAndKeyID but is not nil && this == nil")
	}
	if len(this.Certificate) != len(that1.Certificate) {
		return fmt.Errorf("Certificate this(%v) Not Equal that(%v)", len(this.Certificate), len(that1.Certificate))
	}
	for i := range this.Certificate {
		if !bytes.Equal(this.Certificate[i], that1.Certificate[i]) {
			return fmt.Errorf("Certificate this[%v](%v) Not Equal that[%v](%v)", i, this.Certificate[i], i, that1.Certificate[i])
		}
	}
	if this.KeyID != that1.KeyID {
		return fmt.Errorf("KeyID this(%v) Not Equal that(%v)", this.KeyID, that1.KeyID)
	}
	if !bytes.Equal(this.OCSPStaple, that1.OCSPStaple) {
		return fmt.Errorf("OCSPStaple this(%v) Not Equal that(%v)", this.OCSPStaple, that1.OCSPStaple)
	}
	return nil
}
func (this *CertificateAndKeyID) Equal(that interface{}) bool {
	if that == nil {
		if this == nil {
			return true
		}
		return false
	}

	that1, ok := that.(*CertificateAndKeyID)
	if !ok {
		that2, ok := that.(CertificateAndKeyID)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		if this == nil {
			return true
		}
		return false
	} else if this == nil {
		return false
	}
	if len(this.Certificate) != len(that1.Certificate) {
		return false
	}
	for i := range this.Certificate {
		if !bytes.Equal(this.Certificate[i], that1.Certificate[i]) {
			return false
		}
	}
	if this.KeyID != that1.KeyID {
		return false
	}
	if !bytes.Equal(this.OCSPStaple, that1.OCSPStaple) {
		return false
	}
	return true
}
func (this *TLSConfig) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 17)
	s = append(s, "&proto.TLSConfig{")
	if this.Certificates != nil {
		s = append(s, "Certificates: "+fmt.Sprintf("%#v", this.Certificates)+",\n")
	}
	s = append(s, "RootCAs: "+fmt.Sprintf("%#v", this.RootCAs)+",\n")
	s = append(s, "NextProtos: "+fmt.Sprintf("%#v", this.NextProtos)+",\n")
	s = append(s, "ServerName: "+fmt.Sprintf("%#v", this.ServerName)+",\n")
	s = append(s, "ClientAuth: "+fmt.Sprintf("%#v", this.ClientAuth)+",\n")
	s = append(s, "ClientCAs: "+fmt.Sprintf("%#v", this.ClientCAs)+",\n")
	s = append(s, "CipherSuites: "+fmt.Sprintf("%#v", this.CipherSuites)+",\n")
	s = append(s, "PreferServerCipherSuites: "+fmt.Sprintf("%#v", this.PreferServerCipherSuites)+",\n")
	s = append(s, "SessionTicketsEnabled: "+fmt.Sprintf("%#v", this.SessionTicketsEnabled)+",\n")
	s = append(s, "SessionTicketKeyID: "+fmt.Sprintf("%#v", this.SessionTicketKeyID)+",\n")
	s = append(s, "MinVersion: "+fmt.Sprintf("%#v", this.MinVersion)+",\n")
	s = append(s, "MaxVersion: "+fmt.Sprintf("%#v", this.MaxVersion)+",\n")
	s = append(s, "CurvePreferences: "+fmt.Sprintf("%#v", this.CurvePreferences)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *CertificateAndKeyID) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 7)
	s = append(s, "&proto.CertificateAndKeyID{")
	s = append(s, "Certificate: "+fmt.Sprintf("%#v", this.Certificate)+",\n")
	s = append(s, "KeyID: "+fmt.Sprintf("%#v", this.KeyID)+",\n")
	s = append(s, "OCSPStaple: "+fmt.Sprintf("%#v", this.OCSPStaple)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func valueToGoStringTlsconfig(v interface{}, typ string) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("func(v %v) *%v { return &v } ( %#v )", typ, typ, pv)
}
func (m *TLSConfig) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TLSConfig) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Certificates) > 0 {
		for _, msg := range m.Certificates {
			dAtA[i] = 0xa
			i++
			i = encodeVarintTlsconfig(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	if len(m.RootCAs) > 0 {
		for _, b := range m.RootCAs {
			dAtA[i] = 0x1a
			i++
			i = encodeVarintTlsconfig(dAtA, i, uint64(len(b)))
			i += copy(dAtA[i:], b)
		}
	}
	if len(m.NextProtos) > 0 {
		for _, s := range m.NextProtos {
			dAtA[i] = 0x22
			i++
			l = len(s)
			for l >= 1<<7 {
				dAtA[i] = uint8(uint64(l)&0x7f | 0x80)
				l >>= 7
				i++
			}
			dAtA[i] = uint8(l)
			i++
			i += copy(dAtA[i:], s)
		}
	}
	if len(m.ServerName) > 0 {
		dAtA[i] = 0x2a
		i++
		i = encodeVarintTlsconfig(dAtA, i, uint64(len(m.ServerName)))
		i += copy(dAtA[i:], m.ServerName)
	}
	if m.ClientAuth != 0 {
		dAtA[i] = 0x30
		i++
		i = encodeVarintTlsconfig(dAtA, i, uint64(m.ClientAuth))
	}
	if len(m.ClientCAs) > 0 {
		for _, b := range m.ClientCAs {
			dAtA[i] = 0x3a
			i++
			i = encodeVarintTlsconfig(dAtA, i, uint64(len(b)))
			i += copy(dAtA[i:], b)
		}
	}
	if len(m.CipherSuites) > 0 {
		dAtA2 := make([]byte, len(m.CipherSuites)*10)
		var j1 int
		for _, num := range m.CipherSuites {
			for num >= 1<<7 {
				dAtA2[j1] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j1++
			}
			dAtA2[j1] = uint8(num)
			j1++
		}
		dAtA[i] = 0x42
		i++
		i = encodeVarintTlsconfig(dAtA, i, uint64(j1))
		i += copy(dAtA[i:], dAtA2[:j1])
	}
	if m.PreferServerCipherSuites {
		dAtA[i] = 0x48
		i++
		if m.PreferServerCipherSuites {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i++
	}
	if m.SessionTicketsEnabled {
		dAtA[i] = 0x50
		i++
		if m.SessionTicketsEnabled {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i++
	}
	if len(m.SessionTicketKeyID) > 0 {
		dAtA[i] = 0x5a
		i++
		i = encodeVarintTlsconfig(dAtA, i, uint64(len(m.SessionTicketKeyID)))
		i += copy(dAtA[i:], m.SessionTicketKeyID)
	}
	if m.MinVersion != 0 {
		dAtA[i] = 0x60
		i++
		i = encodeVarintTlsconfig(dAtA, i, uint64(m.MinVersion))
	}
	if m.MaxVersion != 0 {
		dAtA[i] = 0x68
		i++
		i = encodeVarintTlsconfig(dAtA, i, uint64(m.MaxVersion))
	}
	if len(m.CurvePreferences) > 0 {
		dAtA4 := make([]byte, len(m.CurvePreferences)*10)
		var j3 int
		for _, num := range m.CurvePreferences {
			for num >= 1<<7 {
				dAtA4[j3] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j3++
			}
			dAtA4[j3] = uint8(num)
			j3++
		}
		dAtA[i] = 0x72
		i++
		i = encodeVarintTlsconfig(dAtA, i, uint64(j3))
		i += copy(dAtA[i:], dAtA4[:j3])
	}
	return i, nil
}

func (m *CertificateAndKeyID) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CertificateAndKeyID) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Certificate) > 0 {
		for _, b := range m.Certificate {
			dAtA[i] = 0xa
			i++
			i = encodeVarintTlsconfig(dAtA, i, uint64(len(b)))
			i += copy(dAtA[i:], b)
		}
	}
	if len(m.KeyID) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintTlsconfig(dAtA, i, uint64(len(m.KeyID)))
		i += copy(dAtA[i:], m.KeyID)
	}
	if len(m.OCSPStaple) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintTlsconfig(dAtA, i, uint64(len(m.OCSPStaple)))
		i += copy(dAtA[i:], m.OCSPStaple)
	}
	return i, nil
}

func encodeFixed64Tlsconfig(dAtA []byte, offset int, v uint64) int {
	dAtA[offset] = uint8(v)
	dAtA[offset+1] = uint8(v >> 8)
	dAtA[offset+2] = uint8(v >> 16)
	dAtA[offset+3] = uint8(v >> 24)
	dAtA[offset+4] = uint8(v >> 32)
	dAtA[offset+5] = uint8(v >> 40)
	dAtA[offset+6] = uint8(v >> 48)
	dAtA[offset+7] = uint8(v >> 56)
	return offset + 8
}
func encodeFixed32Tlsconfig(dAtA []byte, offset int, v uint32) int {
	dAtA[offset] = uint8(v)
	dAtA[offset+1] = uint8(v >> 8)
	dAtA[offset+2] = uint8(v >> 16)
	dAtA[offset+3] = uint8(v >> 24)
	return offset + 4
}
func encodeVarintTlsconfig(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func NewPopulatedTLSConfig(r randyTlsconfig, easy bool) *TLSConfig {
	this := &TLSConfig{}
	if r.Intn(10) != 0 {
		v1 := r.Intn(5)
		this.Certificates = make([]*CertificateAndKeyID, v1)
		for i := 0; i < v1; i++ {
			this.Certificates[i] = NewPopulatedCertificateAndKeyID(r, easy)
		}
	}
	v2 := r.Intn(10)
	this.RootCAs = make([][]byte, v2)
	for i := 0; i < v2; i++ {
		v3 := r.Intn(100)
		this.RootCAs[i] = make([]byte, v3)
		for j := 0; j < v3; j++ {
			this.RootCAs[i][j] = byte(r.Intn(256))
		}
	}
	v4 := r.Intn(10)
	this.NextProtos = make([]string, v4)
	for i := 0; i < v4; i++ {
		this.NextProtos[i] = string(randStringTlsconfig(r))
	}
	this.ServerName = string(randStringTlsconfig(r))
	this.ClientAuth = ClientAuthType([]int32{0, 1, 2, 3, 4}[r.Intn(5)])
	v5 := r.Intn(10)
	this.ClientCAs = make([][]byte, v5)
	for i := 0; i < v5; i++ {
		v6 := r.Intn(100)
		this.ClientCAs[i] = make([]byte, v6)
		for j := 0; j < v6; j++ {
			this.ClientCAs[i][j] = byte(r.Intn(256))
		}
	}
	v7 := r.Intn(10)
	this.CipherSuites = make([]CipherSuite, v7)
	for i := 0; i < v7; i++ {
		this.CipherSuites[i] = CipherSuite([]int32{0, 49199, 49200, 49191, 49171, 49172, 156, 157, 60, 47, 53, 5, 10, 49159, 49161, 49162, 49169, 49170, 49195, 22016}[r.Intn(20)])
	}
	this.PreferServerCipherSuites = bool(bool(r.Intn(2) == 0))
	this.SessionTicketsEnabled = bool(bool(r.Intn(2) == 0))
	this.SessionTicketKeyID = string(randStringTlsconfig(r))
	this.MinVersion = TLSVersion([]int32{0, 768, 769, 770, 771}[r.Intn(5)])
	this.MaxVersion = TLSVersion([]int32{0, 768, 769, 770, 771}[r.Intn(5)])
	v8 := r.Intn(10)
	this.CurvePreferences = make([]CurveID, v8)
	for i := 0; i < v8; i++ {
		this.CurvePreferences[i] = CurveID([]int32{0, 23, 24, 25}[r.Intn(4)])
	}
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

func NewPopulatedCertificateAndKeyID(r randyTlsconfig, easy bool) *CertificateAndKeyID {
	this := &CertificateAndKeyID{}
	v9 := r.Intn(10)
	this.Certificate = make([][]byte, v9)
	for i := 0; i < v9; i++ {
		v10 := r.Intn(100)
		this.Certificate[i] = make([]byte, v10)
		for j := 0; j < v10; j++ {
			this.Certificate[i][j] = byte(r.Intn(256))
		}
	}
	this.KeyID = string(randStringTlsconfig(r))
	v11 := r.Intn(100)
	this.OCSPStaple = make([]byte, v11)
	for i := 0; i < v11; i++ {
		this.OCSPStaple[i] = byte(r.Intn(256))
	}
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

type randyTlsconfig interface {
	Float32() float32
	Float64() float64
	Int63() int64
	Int31() int32
	Uint32() uint32
	Intn(n int) int
}

func randUTF8RuneTlsconfig(r randyTlsconfig) rune {
	ru := r.Intn(62)
	if ru < 10 {
		return rune(ru + 48)
	} else if ru < 36 {
		return rune(ru + 55)
	}
	return rune(ru + 61)
}
func randStringTlsconfig(r randyTlsconfig) string {
	v12 := r.Intn(100)
	tmps := make([]rune, v12)
	for i := 0; i < v12; i++ {
		tmps[i] = randUTF8RuneTlsconfig(r)
	}
	return string(tmps)
}
func randUnrecognizedTlsconfig(r randyTlsconfig, maxFieldNumber int) (dAtA []byte) {
	l := r.Intn(5)
	for i := 0; i < l; i++ {
		wire := r.Intn(4)
		if wire == 3 {
			wire = 5
		}
		fieldNumber := maxFieldNumber + r.Intn(100)
		dAtA = randFieldTlsconfig(dAtA, r, fieldNumber, wire)
	}
	return dAtA
}
func randFieldTlsconfig(dAtA []byte, r randyTlsconfig, fieldNumber int, wire int) []byte {
	key := uint32(fieldNumber)<<3 | uint32(wire)
	switch wire {
	case 0:
		dAtA = encodeVarintPopulateTlsconfig(dAtA, uint64(key))
		v13 := r.Int63()
		if r.Intn(2) == 0 {
			v13 *= -1
		}
		dAtA = encodeVarintPopulateTlsconfig(dAtA, uint64(v13))
	case 1:
		dAtA = encodeVarintPopulateTlsconfig(dAtA, uint64(key))
		dAtA = append(dAtA, byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)))
	case 2:
		dAtA = encodeVarintPopulateTlsconfig(dAtA, uint64(key))
		ll := r.Intn(100)
		dAtA = encodeVarintPopulateTlsconfig(dAtA, uint64(ll))
		for j := 0; j < ll; j++ {
			dAtA = append(dAtA, byte(r.Intn(256)))
		}
	default:
		dAtA = encodeVarintPopulateTlsconfig(dAtA, uint64(key))
		dAtA = append(dAtA, byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)))
	}
	return dAtA
}
func encodeVarintPopulateTlsconfig(dAtA []byte, v uint64) []byte {
	for v >= 1<<7 {
		dAtA = append(dAtA, uint8(uint64(v)&0x7f|0x80))
		v >>= 7
	}
	dAtA = append(dAtA, uint8(v))
	return dAtA
}
func (m *TLSConfig) Size() (n int) {
	var l int
	_ = l
	if len(m.Certificates) > 0 {
		for _, e := range m.Certificates {
			l = e.Size()
			n += 1 + l + sovTlsconfig(uint64(l))
		}
	}
	if len(m.RootCAs) > 0 {
		for _, b := range m.RootCAs {
			l = len(b)
			n += 1 + l + sovTlsconfig(uint64(l))
		}
	}
	if len(m.NextProtos) > 0 {
		for _, s := range m.NextProtos {
			l = len(s)
			n += 1 + l + sovTlsconfig(uint64(l))
		}
	}
	l = len(m.ServerName)
	if l > 0 {
		n += 1 + l + sovTlsconfig(uint64(l))
	}
	if m.ClientAuth != 0 {
		n += 1 + sovTlsconfig(uint64(m.ClientAuth))
	}
	if len(m.ClientCAs) > 0 {
		for _, b := range m.ClientCAs {
			l = len(b)
			n += 1 + l + sovTlsconfig(uint64(l))
		}
	}
	if len(m.CipherSuites) > 0 {
		l = 0
		for _, e := range m.CipherSuites {
			l += sovTlsconfig(uint64(e))
		}
		n += 1 + sovTlsconfig(uint64(l)) + l
	}
	if m.PreferServerCipherSuites {
		n += 2
	}
	if m.SessionTicketsEnabled {
		n += 2
	}
	l = len(m.SessionTicketKeyID)
	if l > 0 {
		n += 1 + l + sovTlsconfig(uint64(l))
	}
	if m.MinVersion != 0 {
		n += 1 + sovTlsconfig(uint64(m.MinVersion))
	}
	if m.MaxVersion != 0 {
		n += 1 + sovTlsconfig(uint64(m.MaxVersion))
	}
	if len(m.CurvePreferences) > 0 {
		l = 0
		for _, e := range m.CurvePreferences {
			l += sovTlsconfig(uint64(e))
		}
		n += 1 + sovTlsconfig(uint64(l)) + l
	}
	return n
}

func (m *CertificateAndKeyID) Size() (n int) {
	var l int
	_ = l
	if len(m.Certificate) > 0 {
		for _, b := range m.Certificate {
			l = len(b)
			n += 1 + l + sovTlsconfig(uint64(l))
		}
	}
	l = len(m.KeyID)
	if l > 0 {
		n += 1 + l + sovTlsconfig(uint64(l))
	}
	l = len(m.OCSPStaple)
	if l > 0 {
		n += 1 + l + sovTlsconfig(uint64(l))
	}
	return n
}

func sovTlsconfig(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozTlsconfig(x uint64) (n int) {
	return sovTlsconfig(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *TLSConfig) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&TLSConfig{`,
		`Certificates:` + strings.Replace(fmt.Sprintf("%v", this.Certificates), "CertificateAndKeyID", "CertificateAndKeyID", 1) + `,`,
		`RootCAs:` + fmt.Sprintf("%v", this.RootCAs) + `,`,
		`NextProtos:` + fmt.Sprintf("%v", this.NextProtos) + `,`,
		`ServerName:` + fmt.Sprintf("%v", this.ServerName) + `,`,
		`ClientAuth:` + fmt.Sprintf("%v", this.ClientAuth) + `,`,
		`ClientCAs:` + fmt.Sprintf("%v", this.ClientCAs) + `,`,
		`CipherSuites:` + fmt.Sprintf("%v", this.CipherSuites) + `,`,
		`PreferServerCipherSuites:` + fmt.Sprintf("%v", this.PreferServerCipherSuites) + `,`,
		`SessionTicketsEnabled:` + fmt.Sprintf("%v", this.SessionTicketsEnabled) + `,`,
		`SessionTicketKeyID:` + fmt.Sprintf("%v", this.SessionTicketKeyID) + `,`,
		`MinVersion:` + fmt.Sprintf("%v", this.MinVersion) + `,`,
		`MaxVersion:` + fmt.Sprintf("%v", this.MaxVersion) + `,`,
		`CurvePreferences:` + fmt.Sprintf("%v", this.CurvePreferences) + `,`,
		`}`,
	}, "")
	return s
}
func (this *CertificateAndKeyID) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&CertificateAndKeyID{`,
		`Certificate:` + fmt.Sprintf("%v", this.Certificate) + `,`,
		`KeyID:` + fmt.Sprintf("%v", this.KeyID) + `,`,
		`OCSPStaple:` + fmt.Sprintf("%v", this.OCSPStaple) + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringTlsconfig(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *TLSConfig) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTlsconfig
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TLSConfig: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TLSConfig: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Certificates", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTlsconfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTlsconfig
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Certificates = append(m.Certificates, &CertificateAndKeyID{})
			if err := m.Certificates[len(m.Certificates)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RootCAs", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTlsconfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTlsconfig
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RootCAs = append(m.RootCAs, make([]byte, postIndex-iNdEx))
			copy(m.RootCAs[len(m.RootCAs)-1], dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NextProtos", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTlsconfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTlsconfig
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NextProtos = append(m.NextProtos, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ServerName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTlsconfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTlsconfig
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ServerName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClientAuth", wireType)
			}
			m.ClientAuth = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTlsconfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ClientAuth |= (ClientAuthType(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClientCAs", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTlsconfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTlsconfig
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ClientCAs = append(m.ClientCAs, make([]byte, postIndex-iNdEx))
			copy(m.ClientCAs[len(m.ClientCAs)-1], dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType == 0 {
				var v CipherSuite
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowTlsconfig
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= (CipherSuite(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.CipherSuites = append(m.CipherSuites, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowTlsconfig
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= (int(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthTlsconfig
				}
				postIndex := iNdEx + packedLen
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				for iNdEx < postIndex {
					var v CipherSuite
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowTlsconfig
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= (CipherSuite(b) & 0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.CipherSuites = append(m.CipherSuites, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field CipherSuites", wireType)
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PreferServerCipherSuites", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTlsconfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.PreferServerCipherSuites = bool(v != 0)
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SessionTicketsEnabled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTlsconfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.SessionTicketsEnabled = bool(v != 0)
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SessionTicketKeyID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTlsconfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTlsconfig
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SessionTicketKeyID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 12:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinVersion", wireType)
			}
			m.MinVersion = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTlsconfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MinVersion |= (TLSVersion(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 13:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxVersion", wireType)
			}
			m.MaxVersion = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTlsconfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxVersion |= (TLSVersion(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 14:
			if wireType == 0 {
				var v CurveID
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowTlsconfig
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= (CurveID(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.CurvePreferences = append(m.CurvePreferences, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowTlsconfig
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= (int(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthTlsconfig
				}
				postIndex := iNdEx + packedLen
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				for iNdEx < postIndex {
					var v CurveID
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowTlsconfig
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= (CurveID(b) & 0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.CurvePreferences = append(m.CurvePreferences, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field CurvePreferences", wireType)
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTlsconfig(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthTlsconfig
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CertificateAndKeyID) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTlsconfig
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CertificateAndKeyID: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CertificateAndKeyID: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Certificate", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTlsconfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTlsconfig
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Certificate = append(m.Certificate, make([]byte, postIndex-iNdEx))
			copy(m.Certificate[len(m.Certificate)-1], dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field KeyID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTlsconfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTlsconfig
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.KeyID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OCSPStaple", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTlsconfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTlsconfig
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OCSPStaple = append(m.OCSPStaple[:0], dAtA[iNdEx:postIndex]...)
			if m.OCSPStaple == nil {
				m.OCSPStaple = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTlsconfig(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthTlsconfig
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTlsconfig(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTlsconfig
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTlsconfig
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTlsconfig
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthTlsconfig
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowTlsconfig
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipTlsconfig(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthTlsconfig = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTlsconfig   = fmt.Errorf("proto: integer overflow")
)

func init() { proto1.RegisterFile("tlsconfig.proto", fileDescriptorTlsconfig) }

var fileDescriptorTlsconfig = []byte{
	// 1010 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x84, 0x94, 0x4f, 0x50, 0x23, 0x45,
	0x14, 0xc6, 0xe9, 0x1d, 0x12, 0xc8, 0x4b, 0x88, 0x43, 0x6f, 0xb1, 0x8c, 0xb0, 0x4e, 0x46, 0x76,
	0x5d, 0x23, 0xba, 0xb0, 0x84, 0x05, 0xa9, 0xf2, 0x4f, 0x19, 0x26, 0xc3, 0x32, 0xb5, 0x31, 0xe0,
	0x74, 0x16, 0xcb, 0x53, 0x57, 0x18, 0x1a, 0x98, 0x02, 0x32, 0x54, 0x66, 0x42, 0x81, 0xa7, 0x51,
	0x0f, 0x96, 0xde, 0xd4, 0x3d, 0x6a, 0x79, 0xd4, 0x2a, 0xad, 0xd2, 0xa3, 0x55, 0x5e, 0x3c, 0x7a,
	0xdc, 0xa3, 0x27, 0x6a, 0x99, 0x93, 0xc7, 0x3d, 0x7a, 0xb4, 0xba, 0x27, 0x21, 0x93, 0x90, 0xcd,
	0x9e, 0xd2, 0xef, 0x7d, 0xbf, 0xf7, 0xe6, 0xbd, 0x6f, 0x3a, 0x03, 0x2f, 0xf9, 0x87, 0x9e, 0xed,
	0xd6, 0x77, 0x9d, 0xbd, 0xb9, 0xe3, 0x86, 0xeb, 0xbb, 0x38, 0x21, 0x7e, 0xa6, 0xee, 0xee, 0x39,
	0xfe, 0x7e, 0x73, 0x7b, 0xce, 0x76, 0x8f, 0xe6, 0xf7, 0xdc, 0x3d, 0x77, 0x5e, 0xa4, 0xb7, 0x9b,
	0xbb, 0x22, 0x12, 0x81, 0x38, 0x45, 0x55, 0x33, 0x7f, 0x26, 0x20, 0x55, 0x2d, 0x13, 0x5d, 0x74,
	0xc2, 0xef, 0x43, 0xc6, 0x66, 0x0d, 0xdf, 0xd9, 0x75, 0xec, 0x9a, 0xcf, 0x3c, 0x05, 0x69, 0x52,
	0x3e, 0x5d, 0x98, 0x8a, 0xd8, 0x39, 0xbd, 0x23, 0x15, 0xeb, 0x3b, 0x0f, 0xd9, 0x99, 0x59, 0xb2,
	0xba, 0x78, 0x7c, 0x07, 0x46, 0x1b, 0xae, 0xeb, 0x53, 0xbb, 0xe6, 0x29, 0x92, 0x26, 0xe5, 0x33,
	0xab, 0xe9, 0xf0, 0x3c, 0x37, 0x62, 0xb9, 0xae, 0xaf, 0x17, 0x3d, 0x6b, 0x84, 0x8b, 0x7a, 0xcd,
	0xc3, 0x39, 0x48, 0xd7, 0xd9, 0xa9, 0x4f, 0x45, 0x5f, 0x4f, 0x19, 0xd6, 0xa4, 0x7c, 0xca, 0x02,
	0x9e, 0xda, 0x14, 0x19, 0x0e, 0x78, 0xac, 0x71, 0xc2, 0x1a, 0xb4, 0x5e, 0x3b, 0x62, 0x4a, 0x42,
	0x43, 0x1c, 0x88, 0x52, 0x95, 0xda, 0x11, 0xc3, 0xcb, 0x90, 0xb6, 0x0f, 0x1d, 0x56, 0xf7, 0x69,
	0xad, 0xe9, 0xef, 0x2b, 0x49, 0x0d, 0xe5, 0xb3, 0x85, 0x89, 0xf6, 0xa0, 0x42, 0x29, 0x36, 0xfd,
	0xfd, 0xea, 0xd9, 0x31, 0xb3, 0xc0, 0xbe, 0x8c, 0xf1, 0x5b, 0xd0, 0x8a, 0xc4, 0x8c, 0x23, 0x62,
	0xc6, 0xb1, 0xf0, 0x3c, 0x97, 0x8a, 0x6a, 0xf8, 0x94, 0xa9, 0x08, 0xe0, 0x73, 0xbe, 0x0d, 0x63,
	0xb6, 0x73, 0xbc, 0xcf, 0x1a, 0xd4, 0x6b, 0x3a, 0xdc, 0x90, 0x51, 0x4d, 0xca, 0x67, 0x0b, 0xb8,
	0xfd, 0x1c, 0xa1, 0x11, 0x2e, 0x59, 0x19, 0xbb, 0x13, 0x78, 0xf8, 0x3d, 0x98, 0x3e, 0x6e, 0xb0,
	0x5d, 0x5e, 0x18, 0xad, 0xd1, 0xdd, 0x26, 0xa5, 0xa1, 0xfc, 0xa8, 0xa5, 0x44, 0x08, 0x11, 0x84,
	0x1e, 0x2f, 0x5f, 0x86, 0x49, 0x8f, 0x79, 0x9e, 0xe3, 0xd6, 0xa9, 0xef, 0xd8, 0x07, 0xcc, 0xf7,
	0x28, 0xab, 0xd7, 0xb6, 0x0f, 0xd9, 0x8e, 0x02, 0xa2, 0x74, 0xa2, 0x25, 0x57, 0x23, 0xd5, 0x88,
	0x44, 0x6c, 0xc2, 0x44, 0x77, 0x1d, 0x3d, 0x60, 0x67, 0xd4, 0xd9, 0x51, 0xd2, 0xdc, 0xc0, 0xd5,
	0x1b, 0xe1, 0x79, 0x0e, 0x93, 0x78, 0x65, 0xf4, 0x12, 0xb1, 0xd7, 0x9b, 0xdb, 0xc1, 0x05, 0x48,
	0x1f, 0x39, 0x75, 0x7a, 0xc2, 0x1a, 0x5c, 0x51, 0x32, 0xc2, 0xe0, 0xf1, 0xd6, 0xe2, 0xd5, 0x32,
	0xd9, 0x8a, 0x04, 0x0b, 0x8e, 0x9c, 0x7a, 0xeb, 0x2c, 0x6a, 0x6a, 0xa7, 0x97, 0x35, 0x63, 0xcf,
	0xaf, 0xa9, 0x9d, 0xb6, 0x6b, 0xde, 0x81, 0x71, 0xbb, 0xd9, 0x38, 0x61, 0x34, 0x32, 0x83, 0xd5,
	0x6d, 0xe6, 0x29, 0x59, 0x61, 0x73, 0xb6, 0x6d, 0x33, 0xd7, 0xcd, 0x92, 0x25, 0x0b, 0x70, 0xb3,
	0xc3, 0xcd, 0x7c, 0x0a, 0xd7, 0xfb, 0x5c, 0x4a, 0xac, 0x41, 0x3a, 0x76, 0x2d, 0xc5, 0x2d, 0xce,
	0x58, 0xf1, 0x14, 0xd6, 0x20, 0xd9, 0x72, 0xe6, 0x9a, 0x70, 0x26, 0x15, 0x9e, 0xe7, 0x12, 0x91,
	0x19, 0x89, 0x03, 0xb1, 0x7f, 0x0e, 0xd2, 0x1b, 0x3a, 0xd9, 0xa4, 0x9e, 0x5f, 0x3b, 0x3e, 0x64,
	0x8a, 0xa4, 0xa1, 0x7c, 0xc6, 0x02, 0x9e, 0x22, 0x22, 0x33, 0x7b, 0x0a, 0xd0, 0x59, 0x09, 0x4f,
	0xc1, 0x8d, 0x4e, 0x44, 0x1f, 0x55, 0xc8, 0xa6, 0xa1, 0x9b, 0x6b, 0xa6, 0x51, 0x92, 0x87, 0x30,
	0x86, 0xb1, 0x2d, 0xc3, 0x22, 0xe6, 0x46, 0x85, 0x12, 0x52, 0x5e, 0xbc, 0x27, 0x07, 0xc9, 0x78,
	0xae, 0x5a, 0x26, 0x0b, 0xf7, 0xe4, 0xcf, 0xae, 0xe4, 0x16, 0xe4, 0xcf, 0xaf, 0xe4, 0x0a, 0xf2,
	0x17, 0xc9, 0xd9, 0x1f, 0x11, 0x64, 0xbb, 0xaf, 0x38, 0xc6, 0x90, 0xad, 0x6c, 0x50, 0xbd, 0x6c,
	0x1a, 0x95, 0x2a, 0xd5, 0x0d, 0xab, 0x2a, 0x0f, 0xe1, 0x49, 0xb8, 0x6e, 0x19, 0x1f, 0x3d, 0x32,
	0x48, 0xb5, 0x4b, 0x40, 0x78, 0x1a, 0x26, 0xb9, 0x60, 0x5a, 0x06, 0x2d, 0x56, 0x3e, 0xe9, 0x12,
	0xaf, 0xe1, 0x1c, 0x4c, 0x6f, 0x19, 0x96, 0xb9, 0xd6, 0x95, 0xa7, 0xe6, 0x1a, 0x7d, 0x60, 0x6e,
	0x19, 0x15, 0x59, 0xc2, 0x33, 0xa0, 0x76, 0xaa, 0x4b, 0xf4, 0x2a, 0x2c, 0x0f, 0xcf, 0x3e, 0x4e,
	0x42, 0x3a, 0x76, 0xa1, 0xf9, 0x13, 0x63, 0x61, 0x8f, 0x3d, 0x6f, 0xc2, 0x6b, 0xd5, 0x32, 0xa1,
	0x86, 0x5e, 0x5a, 0x37, 0xa8, 0x45, 0x8a, 0xf4, 0x63, 0xb3, 0xba, 0x4e, 0x8b, 0x06, 0xa1, 0x0b,
	0x85, 0x15, 0xfa, 0x40, 0xff, 0x90, 0x92, 0xf5, 0x62, 0x61, 0x69, 0x59, 0xfe, 0x2d, 0x90, 0x06,
	0xc0, 0x85, 0xa5, 0xe5, 0x36, 0xbc, 0xb8, 0x72, 0x5f, 0xfe, 0x7d, 0x20, 0xcc, 0x3b, 0xeb, 0xab,
	0x7a, 0xbb, 0xf3, 0x4f, 0x81, 0x84, 0xf3, 0x30, 0xf3, 0x62, 0x58, 0xfe, 0x6e, 0x20, 0xc9, 0x67,
	0x68, 0x93, 0x8f, 0x03, 0x09, 0xdf, 0x86, 0x1c, 0x27, 0x07, 0x2d, 0xf5, 0x3d, 0xea, 0x4b, 0xf5,
	0x6c, 0xf3, 0x03, 0xc2, 0xb7, 0x9e, 0xd3, 0x2b, 0xb6, 0xc6, 0xbb, 0x58, 0x83, 0x9b, 0x83, 0x20,
	0x79, 0xbe, 0x2f, 0x11, 0x1f, 0x7b, 0x09, 0xdf, 0x04, 0xa5, 0x8b, 0xb0, 0xf4, 0xfb, 0xa2, 0x07,
	0x57, 0x13, 0xf8, 0x55, 0x78, 0xa5, 0x4b, 0x5d, 0x2c, 0x19, 0x84, 0x1a, 0x25, 0xe3, 0xb2, 0x01,
	0xe0, 0x3b, 0xa0, 0x75, 0xfc, 0x31, 0xf4, 0x52, 0xbf, 0x46, 0x5f, 0x06, 0x12, 0x9e, 0x85, 0xdb,
	0x7d, 0xb9, 0xde, 0xa1, 0xbf, 0x7a, 0x01, 0x1b, 0x1f, 0xff, 0x6b, 0xe1, 0xba, 0xda, 0xe7, 0xfd,
	0xc4, 0x9f, 0xfe, 0x4d, 0x20, 0xe1, 0x37, 0xe0, 0x56, 0x1f, 0xea, 0xca, 0x3a, 0xdf, 0x06, 0x12,
	0xbe, 0x0b, 0xaf, 0x0f, 0x1c, 0x34, 0xf6, 0x3a, 0x7f, 0x09, 0x24, 0x3c, 0x09, 0xe3, 0x1c, 0x5f,
	0x2b, 0x96, 0xcb, 0xab, 0x45, 0xfd, 0x21, 0x25, 0x3a, 0xd9, 0x92, 0x83, 0x5f, 0xd1, 0xec, 0x07,
	0x30, 0xd2, 0xfa, 0x96, 0xf1, 0x3f, 0x67, 0xeb, 0xd8, 0xf3, 0x6f, 0x18, 0x85, 0xe1, 0x4d, 0xde,
	0x68, 0x52, 0x9c, 0xf8, 0xbb, 0x57, 0xc4, 0x69, 0xa9, 0xb0, 0x20, 0xbf, 0xbc, 0xba, 0xf2, 0xe4,
	0x42, 0x1d, 0xfa, 0xe7, 0x42, 0x1d, 0x7a, 0x7a, 0xa1, 0xa2, 0x67, 0x17, 0x2a, 0xfa, 0xef, 0x42,
	0x45, 0x41, 0xa8, 0xa2, 0x9f, 0x43, 0x15, 0xfd, 0x11, 0xaa, 0xe8, 0xaf, 0x50, 0x45, 0x7f, 0x87,
	0x2a, 0x7a, 0x12, 0xaa, 0xe8, 0x69, 0xa8, 0xa2, 0x7f, 0x43, 0x75, 0xe8, 0x59, 0xa8, 0xa2, 0xed,
	0xa4, 0xf8, 0x96, 0x2e, 0xfe, 0x1f, 0x00, 0x00, 0xff, 0xff, 0xf9, 0xd3, 0x16, 0x41, 0x38, 0x08,
	0x00, 0x00,
}
