// Code generated by protoc-gen-gogo.
// source: verifierconfig.proto
// DO NOT EDIT!

package proto

import proto1 "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/protobuf/gogoproto"

import bytes "bytes"

import strings "strings"
import reflect "reflect"

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type VerifierConfig struct {
	ID                   uint64              `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	SigningKeyID         string              `protobuf:"bytes,2,opt,name=signing_key_id,json=signingKeyId,proto3" json:"signing_key_id,omitempty"`
	Realm                string              `protobuf:"bytes,3,opt,name=realm,proto3" json:"realm,omitempty"`
	TLS                  *TLSConfig          `protobuf:"bytes,4,opt,name=tls" json:"tls,omitempty"`
	KeyserverAddr        string              `protobuf:"bytes,5,opt,name=keyserver_addr,json=keyserverAddr,proto3" json:"keyserver_addr,omitempty"`
	InitialKeyserverAuth AuthorizationPolicy `protobuf:"bytes,6,opt,name=initial_keyserver_auth,json=initialKeyserverAuth" json:"initial_keyserver_auth"`
	TreeNonce            []byte              `protobuf:"bytes,7,opt,name=tree_nonce,json=treeNonce,proto3" json:"tree_nonce,omitempty"`
	// LevelDBPath specifies the directory in which the database is stored.
	// Nothing else should use this directory.
	LevelDBPath string `protobuf:"bytes,8,opt,name=leveldb_path,json=leveldbPath,proto3" json:"leveldb_path,omitempty"`
}

func (m *VerifierConfig) Reset()                    { *m = VerifierConfig{} }
func (*VerifierConfig) ProtoMessage()               {}
func (*VerifierConfig) Descriptor() ([]byte, []int) { return fileDescriptorVerifierconfig, []int{0} }

func (m *VerifierConfig) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *VerifierConfig) GetSigningKeyID() string {
	if m != nil {
		return m.SigningKeyID
	}
	return ""
}

func (m *VerifierConfig) GetRealm() string {
	if m != nil {
		return m.Realm
	}
	return ""
}

func (m *VerifierConfig) GetTLS() *TLSConfig {
	if m != nil {
		return m.TLS
	}
	return nil
}

func (m *VerifierConfig) GetKeyserverAddr() string {
	if m != nil {
		return m.KeyserverAddr
	}
	return ""
}

func (m *VerifierConfig) GetInitialKeyserverAuth() AuthorizationPolicy {
	if m != nil {
		return m.InitialKeyserverAuth
	}
	return AuthorizationPolicy{}
}

func (m *VerifierConfig) GetTreeNonce() []byte {
	if m != nil {
		return m.TreeNonce
	}
	return nil
}

func (m *VerifierConfig) GetLevelDBPath() string {
	if m != nil {
		return m.LevelDBPath
	}
	return ""
}

func init() {
	proto1.RegisterType((*VerifierConfig)(nil), "proto.VerifierConfig")
}
func (this *VerifierConfig) VerboseEqual(that interface{}) error {
	if that == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that == nil && this != nil")
	}

	that1, ok := that.(*VerifierConfig)
	if !ok {
		that2, ok := that.(VerifierConfig)
		if ok {
			that1 = &that2
		} else {
			return fmt.Errorf("that is not of type *VerifierConfig")
		}
	}
	if that1 == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that is type *VerifierConfig but is nil && this != nil")
	} else if this == nil {
		return fmt.Errorf("that is type *VerifierConfig but is not nil && this == nil")
	}
	if this.ID != that1.ID {
		return fmt.Errorf("ID this(%v) Not Equal that(%v)", this.ID, that1.ID)
	}
	if this.SigningKeyID != that1.SigningKeyID {
		return fmt.Errorf("SigningKeyID this(%v) Not Equal that(%v)", this.SigningKeyID, that1.SigningKeyID)
	}
	if this.Realm != that1.Realm {
		return fmt.Errorf("Realm this(%v) Not Equal that(%v)", this.Realm, that1.Realm)
	}
	if !this.TLS.Equal(that1.TLS) {
		return fmt.Errorf("TLS this(%v) Not Equal that(%v)", this.TLS, that1.TLS)
	}
	if this.KeyserverAddr != that1.KeyserverAddr {
		return fmt.Errorf("KeyserverAddr this(%v) Not Equal that(%v)", this.KeyserverAddr, that1.KeyserverAddr)
	}
	if !this.InitialKeyserverAuth.Equal(&that1.InitialKeyserverAuth) {
		return fmt.Errorf("InitialKeyserverAuth this(%v) Not Equal that(%v)", this.InitialKeyserverAuth, that1.InitialKeyserverAuth)
	}
	if !bytes.Equal(this.TreeNonce, that1.TreeNonce) {
		return fmt.Errorf("TreeNonce this(%v) Not Equal that(%v)", this.TreeNonce, that1.TreeNonce)
	}
	if this.LevelDBPath != that1.LevelDBPath {
		return fmt.Errorf("LevelDBPath this(%v) Not Equal that(%v)", this.LevelDBPath, that1.LevelDBPath)
	}
	return nil
}
func (this *VerifierConfig) Equal(that interface{}) bool {
	if that == nil {
		if this == nil {
			return true
		}
		return false
	}

	that1, ok := that.(*VerifierConfig)
	if !ok {
		that2, ok := that.(VerifierConfig)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		if this == nil {
			return true
		}
		return false
	} else if this == nil {
		return false
	}
	if this.ID != that1.ID {
		return false
	}
	if this.SigningKeyID != that1.SigningKeyID {
		return false
	}
	if this.Realm != that1.Realm {
		return false
	}
	if !this.TLS.Equal(that1.TLS) {
		return false
	}
	if this.KeyserverAddr != that1.KeyserverAddr {
		return false
	}
	if !this.InitialKeyserverAuth.Equal(&that1.InitialKeyserverAuth) {
		return false
	}
	if !bytes.Equal(this.TreeNonce, that1.TreeNonce) {
		return false
	}
	if this.LevelDBPath != that1.LevelDBPath {
		return false
	}
	return true
}
func (this *VerifierConfig) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 12)
	s = append(s, "&proto.VerifierConfig{")
	s = append(s, "ID: "+fmt.Sprintf("%#v", this.ID)+",\n")
	s = append(s, "SigningKeyID: "+fmt.Sprintf("%#v", this.SigningKeyID)+",\n")
	s = append(s, "Realm: "+fmt.Sprintf("%#v", this.Realm)+",\n")
	if this.TLS != nil {
		s = append(s, "TLS: "+fmt.Sprintf("%#v", this.TLS)+",\n")
	}
	s = append(s, "KeyserverAddr: "+fmt.Sprintf("%#v", this.KeyserverAddr)+",\n")
	s = append(s, "InitialKeyserverAuth: "+strings.Replace(this.InitialKeyserverAuth.GoString(), `&`, ``, 1)+",\n")
	s = append(s, "TreeNonce: "+fmt.Sprintf("%#v", this.TreeNonce)+",\n")
	s = append(s, "LevelDBPath: "+fmt.Sprintf("%#v", this.LevelDBPath)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func valueToGoStringVerifierconfig(v interface{}, typ string) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("func(v %v) *%v { return &v } ( %#v )", typ, typ, pv)
}
func (m *VerifierConfig) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *VerifierConfig) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.ID != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintVerifierconfig(dAtA, i, uint64(m.ID))
	}
	if len(m.SigningKeyID) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintVerifierconfig(dAtA, i, uint64(len(m.SigningKeyID)))
		i += copy(dAtA[i:], m.SigningKeyID)
	}
	if len(m.Realm) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintVerifierconfig(dAtA, i, uint64(len(m.Realm)))
		i += copy(dAtA[i:], m.Realm)
	}
	if m.TLS != nil {
		dAtA[i] = 0x22
		i++
		i = encodeVarintVerifierconfig(dAtA, i, uint64(m.TLS.Size()))
		n1, err := m.TLS.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n1
	}
	if len(m.KeyserverAddr) > 0 {
		dAtA[i] = 0x2a
		i++
		i = encodeVarintVerifierconfig(dAtA, i, uint64(len(m.KeyserverAddr)))
		i += copy(dAtA[i:], m.KeyserverAddr)
	}
	dAtA[i] = 0x32
	i++
	i = encodeVarintVerifierconfig(dAtA, i, uint64(m.InitialKeyserverAuth.Size()))
	n2, err := m.InitialKeyserverAuth.MarshalTo(dAtA[i:])
	if err != nil {
		return 0, err
	}
	i += n2
	if len(m.TreeNonce) > 0 {
		dAtA[i] = 0x3a
		i++
		i = encodeVarintVerifierconfig(dAtA, i, uint64(len(m.TreeNonce)))
		i += copy(dAtA[i:], m.TreeNonce)
	}
	if len(m.LevelDBPath) > 0 {
		dAtA[i] = 0x42
		i++
		i = encodeVarintVerifierconfig(dAtA, i, uint64(len(m.LevelDBPath)))
		i += copy(dAtA[i:], m.LevelDBPath)
	}
	return i, nil
}

func encodeFixed64Verifierconfig(dAtA []byte, offset int, v uint64) int {
	dAtA[offset] = uint8(v)
	dAtA[offset+1] = uint8(v >> 8)
	dAtA[offset+2] = uint8(v >> 16)
	dAtA[offset+3] = uint8(v >> 24)
	dAtA[offset+4] = uint8(v >> 32)
	dAtA[offset+5] = uint8(v >> 40)
	dAtA[offset+6] = uint8(v >> 48)
	dAtA[offset+7] = uint8(v >> 56)
	return offset + 8
}
func encodeFixed32Verifierconfig(dAtA []byte, offset int, v uint32) int {
	dAtA[offset] = uint8(v)
	dAtA[offset+1] = uint8(v >> 8)
	dAtA[offset+2] = uint8(v >> 16)
	dAtA[offset+3] = uint8(v >> 24)
	return offset + 4
}
func encodeVarintVerifierconfig(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func NewPopulatedVerifierConfig(r randyVerifierconfig, easy bool) *VerifierConfig {
	this := &VerifierConfig{}
	this.ID = uint64(uint64(r.Uint32()))
	this.SigningKeyID = string(randStringVerifierconfig(r))
	this.Realm = string(randStringVerifierconfig(r))
	if r.Intn(10) != 0 {
		this.TLS = NewPopulatedTLSConfig(r, easy)
	}
	this.KeyserverAddr = string(randStringVerifierconfig(r))
	v1 := NewPopulatedAuthorizationPolicy(r, easy)
	this.InitialKeyserverAuth = *v1
	v2 := r.Intn(100)
	this.TreeNonce = make([]byte, v2)
	for i := 0; i < v2; i++ {
		this.TreeNonce[i] = byte(r.Intn(256))
	}
	this.LevelDBPath = string(randStringVerifierconfig(r))
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

type randyVerifierconfig interface {
	Float32() float32
	Float64() float64
	Int63() int64
	Int31() int32
	Uint32() uint32
	Intn(n int) int
}

func randUTF8RuneVerifierconfig(r randyVerifierconfig) rune {
	ru := r.Intn(62)
	if ru < 10 {
		return rune(ru + 48)
	} else if ru < 36 {
		return rune(ru + 55)
	}
	return rune(ru + 61)
}
func randStringVerifierconfig(r randyVerifierconfig) string {
	v3 := r.Intn(100)
	tmps := make([]rune, v3)
	for i := 0; i < v3; i++ {
		tmps[i] = randUTF8RuneVerifierconfig(r)
	}
	return string(tmps)
}
func randUnrecognizedVerifierconfig(r randyVerifierconfig, maxFieldNumber int) (dAtA []byte) {
	l := r.Intn(5)
	for i := 0; i < l; i++ {
		wire := r.Intn(4)
		if wire == 3 {
			wire = 5
		}
		fieldNumber := maxFieldNumber + r.Intn(100)
		dAtA = randFieldVerifierconfig(dAtA, r, fieldNumber, wire)
	}
	return dAtA
}
func randFieldVerifierconfig(dAtA []byte, r randyVerifierconfig, fieldNumber int, wire int) []byte {
	key := uint32(fieldNumber)<<3 | uint32(wire)
	switch wire {
	case 0:
		dAtA = encodeVarintPopulateVerifierconfig(dAtA, uint64(key))
		v4 := r.Int63()
		if r.Intn(2) == 0 {
			v4 *= -1
		}
		dAtA = encodeVarintPopulateVerifierconfig(dAtA, uint64(v4))
	case 1:
		dAtA = encodeVarintPopulateVerifierconfig(dAtA, uint64(key))
		dAtA = append(dAtA, byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)))
	case 2:
		dAtA = encodeVarintPopulateVerifierconfig(dAtA, uint64(key))
		ll := r.Intn(100)
		dAtA = encodeVarintPopulateVerifierconfig(dAtA, uint64(ll))
		for j := 0; j < ll; j++ {
			dAtA = append(dAtA, byte(r.Intn(256)))
		}
	default:
		dAtA = encodeVarintPopulateVerifierconfig(dAtA, uint64(key))
		dAtA = append(dAtA, byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)))
	}
	return dAtA
}
func encodeVarintPopulateVerifierconfig(dAtA []byte, v uint64) []byte {
	for v >= 1<<7 {
		dAtA = append(dAtA, uint8(uint64(v)&0x7f|0x80))
		v >>= 7
	}
	dAtA = append(dAtA, uint8(v))
	return dAtA
}
func (m *VerifierConfig) Size() (n int) {
	var l int
	_ = l
	if m.ID != 0 {
		n += 1 + sovVerifierconfig(uint64(m.ID))
	}
	l = len(m.SigningKeyID)
	if l > 0 {
		n += 1 + l + sovVerifierconfig(uint64(l))
	}
	l = len(m.Realm)
	if l > 0 {
		n += 1 + l + sovVerifierconfig(uint64(l))
	}
	if m.TLS != nil {
		l = m.TLS.Size()
		n += 1 + l + sovVerifierconfig(uint64(l))
	}
	l = len(m.KeyserverAddr)
	if l > 0 {
		n += 1 + l + sovVerifierconfig(uint64(l))
	}
	l = m.InitialKeyserverAuth.Size()
	n += 1 + l + sovVerifierconfig(uint64(l))
	l = len(m.TreeNonce)
	if l > 0 {
		n += 1 + l + sovVerifierconfig(uint64(l))
	}
	l = len(m.LevelDBPath)
	if l > 0 {
		n += 1 + l + sovVerifierconfig(uint64(l))
	}
	return n
}

func sovVerifierconfig(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozVerifierconfig(x uint64) (n int) {
	return sovVerifierconfig(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *VerifierConfig) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&VerifierConfig{`,
		`ID:` + fmt.Sprintf("%v", this.ID) + `,`,
		`SigningKeyID:` + fmt.Sprintf("%v", this.SigningKeyID) + `,`,
		`Realm:` + fmt.Sprintf("%v", this.Realm) + `,`,
		`TLS:` + strings.Replace(fmt.Sprintf("%v", this.TLS), "TLSConfig", "TLSConfig", 1) + `,`,
		`KeyserverAddr:` + fmt.Sprintf("%v", this.KeyserverAddr) + `,`,
		`InitialKeyserverAuth:` + strings.Replace(strings.Replace(this.InitialKeyserverAuth.String(), "AuthorizationPolicy", "AuthorizationPolicy", 1), `&`, ``, 1) + `,`,
		`TreeNonce:` + fmt.Sprintf("%v", this.TreeNonce) + `,`,
		`LevelDBPath:` + fmt.Sprintf("%v", this.LevelDBPath) + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringVerifierconfig(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *VerifierConfig) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowVerifierconfig
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: VerifierConfig: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: VerifierConfig: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ID", wireType)
			}
			m.ID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVerifierconfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ID |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SigningKeyID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVerifierconfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVerifierconfig
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SigningKeyID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Realm", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVerifierconfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVerifierconfig
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Realm = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TLS", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVerifierconfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthVerifierconfig
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.TLS == nil {
				m.TLS = &TLSConfig{}
			}
			if err := m.TLS.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field KeyserverAddr", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVerifierconfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVerifierconfig
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.KeyserverAddr = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field InitialKeyserverAuth", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVerifierconfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthVerifierconfig
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.InitialKeyserverAuth.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TreeNonce", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVerifierconfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthVerifierconfig
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TreeNonce = append(m.TreeNonce[:0], dAtA[iNdEx:postIndex]...)
			if m.TreeNonce == nil {
				m.TreeNonce = []byte{}
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LevelDBPath", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVerifierconfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVerifierconfig
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LevelDBPath = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipVerifierconfig(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthVerifierconfig
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipVerifierconfig(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowVerifierconfig
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowVerifierconfig
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowVerifierconfig
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthVerifierconfig
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowVerifierconfig
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipVerifierconfig(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthVerifierconfig = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowVerifierconfig   = fmt.Errorf("proto: integer overflow")
)

func init() { proto1.RegisterFile("verifierconfig.proto", fileDescriptorVerifierconfig) }

var fileDescriptorVerifierconfig = []byte{
	// 428 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x4c, 0x90, 0x3f, 0x6b, 0xdb, 0x40,
	0x18, 0xc6, 0x7d, 0xf2, 0x9f, 0x34, 0x67, 0xd5, 0x09, 0x87, 0x09, 0xc2, 0xd0, 0x93, 0x29, 0x14,
	0x0c, 0xa5, 0x0e, 0xa4, 0x50, 0xba, 0x46, 0xf5, 0x12, 0x62, 0x4a, 0x90, 0x43, 0x56, 0x21, 0xeb,
	0xce, 0xd2, 0x4b, 0x14, 0x5d, 0x38, 0x9d, 0x0c, 0xee, 0xd4, 0x8f, 0xd3, 0x8f, 0xd0, 0xb1, 0x63,
	0xc6, 0x8c, 0x9d, 0x44, 0x74, 0x53, 0xc7, 0x2c, 0x85, 0x8e, 0x45, 0x27, 0x91, 0x64, 0x92, 0x7e,
	0xcf, 0x3d, 0xef, 0xf3, 0xbc, 0x77, 0x78, 0xbc, 0xe5, 0x12, 0x36, 0xc0, 0x65, 0x24, 0xb2, 0x0d,
	0xc4, 0xf3, 0x5b, 0x29, 0x94, 0x20, 0x7d, 0xf3, 0x99, 0x7c, 0x88, 0x41, 0x25, 0xc5, 0x7a, 0x1e,
	0x89, 0x9b, 0xe3, 0x58, 0xc4, 0xe2, 0xd8, 0xc8, 0xeb, 0x62, 0x63, 0xc8, 0x80, 0xf9, 0x6b, 0xa6,
	0x26, 0x07, 0x2a, 0xcd, 0x5f, 0xc6, 0x4c, 0xec, 0x28, 0x05, 0x9e, 0xa9, 0x86, 0xde, 0xfe, 0xb5,
	0xf0, 0xe8, 0xaa, 0x6d, 0xfb, 0x62, 0x6c, 0xe4, 0x08, 0x5b, 0xc0, 0x1c, 0x34, 0x45, 0xb3, 0x9e,
	0x37, 0xd0, 0xa5, 0x6b, 0x9d, 0x2d, 0x7c, 0x0b, 0x18, 0xf9, 0x84, 0x47, 0x39, 0xc4, 0x19, 0x64,
	0x71, 0x70, 0xcd, 0x77, 0x01, 0x30, 0xc7, 0x9a, 0xa2, 0xd9, 0xbe, 0x77, 0xa8, 0x4b, 0xd7, 0x5e,
	0x35, 0x27, 0xe7, 0x7c, 0x77, 0xb6, 0xf0, 0xed, 0xfc, 0x99, 0x18, 0x19, 0xe3, 0xbe, 0xe4, 0x61,
	0x7a, 0xe3, 0x74, 0x6b, 0xbb, 0xdf, 0x00, 0x79, 0x8f, 0xbb, 0x2a, 0xcd, 0x9d, 0xde, 0x14, 0xcd,
	0x86, 0x27, 0x87, 0xcd, 0x36, 0xf3, 0xcb, 0xe5, 0xaa, 0x59, 0xc2, 0xdb, 0xd3, 0xa5, 0xdb, 0xbd,
	0x5c, 0xae, 0xfc, 0xda, 0x45, 0xde, 0xe1, 0xd1, 0x35, 0xdf, 0xe5, 0x5c, 0x6e, 0xb9, 0x0c, 0x42,
	0xc6, 0xa4, 0xd3, 0x37, 0x59, 0xaf, 0x9f, 0xd4, 0x53, 0xc6, 0x24, 0xb9, 0xc2, 0x47, 0x90, 0x81,
	0x82, 0x30, 0x0d, 0x5e, 0xd8, 0x0b, 0x95, 0x38, 0x03, 0x53, 0x33, 0x69, 0x6b, 0x4e, 0x0b, 0x95,
	0x08, 0x09, 0xdf, 0x42, 0x05, 0x22, 0xbb, 0x10, 0x29, 0x44, 0x3b, 0xaf, 0x77, 0x57, 0xba, 0x1d,
	0x7f, 0xdc, 0xce, 0x9f, 0x3f, 0xe5, 0x16, 0x2a, 0x21, 0x6f, 0x30, 0x56, 0x92, 0xf3, 0x20, 0x13,
	0x59, 0xc4, 0x9d, 0xbd, 0x29, 0x9a, 0xd9, 0xfe, 0x7e, 0xad, 0x7c, 0xad, 0x05, 0x72, 0x82, 0xed,
	0x94, 0x6f, 0x79, 0xca, 0xd6, 0xc1, 0x6d, 0xa8, 0x12, 0xe7, 0x95, 0x79, 0x96, 0x03, 0x5d, 0xba,
	0xc3, 0x65, 0xad, 0x2f, 0xbc, 0x8b, 0x50, 0x25, 0xfe, 0xb0, 0x35, 0xd5, 0xe0, 0x7d, 0xbe, 0xaf,
	0x68, 0xe7, 0x77, 0x45, 0x3b, 0x0f, 0x15, 0x45, 0x8f, 0x15, 0x45, 0xff, 0x2a, 0x8a, 0xbe, 0x6b,
	0x8a, 0x7e, 0x68, 0x8a, 0x7e, 0x6a, 0x8a, 0x7e, 0x69, 0x8a, 0xee, 0x34, 0x45, 0xf7, 0x9a, 0xa2,
	0x07, 0x4d, 0xd1, 0x1f, 0x4d, 0x3b, 0x8f, 0x9a, 0xa2, 0xf5, 0xc0, 0xdc, 0xe1, 0xe3, 0xff, 0x00,
	0x00, 0x00, 0xff, 0xff, 0xd8, 0xd8, 0x48, 0x5d, 0x25, 0x02, 0x00, 0x00,
}
